config/routes.rb
Rails.application.routes.draw do

  resources :tests
  get 'homes/index'

  get 'homes/show'
 get 'personnels/index'
  get 'achievements/index'
  resources :admins
  resources :personnels
  resources :companylicens
  resources :achievements
  resources :clas
  resources :homes

  root 'homes#index'

end

app/models/cla.rb
class Cla < ActiveRecord::Base
end

app/controllers/clas_controller.rb
class ClasController < ApplicationController
  before_action :set_cla, only: [:show, :edit, :update, :destroy]

  # GET /clas
  # GET /clas.json
  def index
    @clas = Cla.all
  end

  # GET /clas/1
  # GET /clas/1.json
  def show
  end

  # GET /clas/new
  def new
    @cla = Cla.new
  end

  # GET /clas/1/edit
  def edit
  end

  # POST /clas
  # POST /clas.json
  def create
    @cla = Cla.new(cla_params)

    respond_to do |format|
      if @cla.save
        format.html { redirect_to @cla, notice: 'Cla was successfully created.' }
        format.json { render :show, status: :created, location: @cla }
      else
        format.html { render :new }
        format.json { render json: @cla.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clas/1
  # PATCH/PUT /clas/1.json
  def update
    respond_to do |format|
      if @cla.update(cla_params)
        format.html { redirect_to @cla, notice: 'Cla was successfully updated.' }
        format.json { render :show, status: :ok, location: @cla }
      else
        format.html { render :edit }
        format.json { render json: @cla.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clas/1
  # DELETE /clas/1.json
  def destroy
    @cla.destroy
    respond_to do |format|
      format.html { redirect_to clas_url, notice: 'Cla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cla
      @cla = Cla.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cla_params
      params.require(:cla).permit(:name)
    end
end

app/helpers/clas_helper.rb
module ClasHelper
end

app/views/clas/_form.html.erb
<%= form_for(@cla) do |f| %>
  <% if @cla.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cla.errors.count, "error") %> prohibited this cla from being saved:</h2>

      <ul>
      <% @cla.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clas/edit.html.erb
<h1>Editing Cla</h1>

<%= render 'form' %>

<%= link_to 'Show', @cla %> |
<%= link_to 'Back', clas_path %>

app/views/clas/index.html.erb
<%=render "head"%>



<p id="notice"><%= notice %></p>

<h1>Listing Clas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clas.each do |cla| %>
      <tr>
        <td><%= cla.name %></td>
        <td><%= link_to 'Show', cla %></td>
        <td><%= link_to 'Edit', edit_cla_path(cla) %></td>
        <td><%= link_to 'Destroy', cla, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cla', new_cla_path %>

app/views/clas/new.html.erb
<h1>New Cla</h1>

<%= render 'form' %>

<%= link_to 'Back', clas_path %>

app/views/clas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cla.name %>
</p>

<%= link_to 'Edit', edit_cla_path(@cla) %> |
<%= link_to 'Back', clas_path %>