config/routes.rb
Rails.application.routes.draw do

  resources :tests
  get 'homes/index'

  get 'homes/show'
 get 'personnels/index'
  get 'achievements/index'
  resources :admins
  resources :personnels
  resources :companylicens
  resources :achievements
  resources :clas
  resources :homes

  root 'homes#index'

end

app/models/companylicen.rb
class Companylicen < ActiveRecord::Base
  mount_uploader :safelicen, SafelicenUploader
  mount_uploader :forconmanquacert, ForconmanquacertUploader
  mount_uploader :statut, StatutUploader
  mount_uploader :threesyscert, ThreesyscertUploader
  mount_uploader :taxcert, TaxcertUploader
  mount_uploader :creditrat, CreditratUploader
  mount_uploader :finastatement, FinastatementUploader
  mount_uploader :orgcode, OrgcodeUploader
  mount_uploader :nolitproof, NolitproofUploader
  mount_uploader :nobankcert, NobankcertUploader
  mount_uploader :certofaward, CertofawardUploader
end

app/controllers/companylicens_controller.rb
class CompanylicensController < ApplicationController
  before_action :set_companylicen, only: [:show, :edit, :update, :destroy]

  # GET /companylicens
  # GET /companylicens.json
  def index
    @companylicens = Companylicen.all
  end

  # GET /companylicens/1
  # GET /companylicens/1.json
  def show
  end

  # GET /companylicens/new
  def new
    @companylicen = Companylicen.new
  end

  # GET /companylicens/1/edit
  def edit
  end

  # POST /companylicens
  # POST /companylicens.json
  def create
    @companylicen = Companylicen.new(companylicen_params)

    respond_to do |format|
      if @companylicen.save
        format.html { redirect_to @companylicen, notice: 'Companylicen was successfully created.' }
        format.json { render :show, status: :created, location: @companylicen }
      else
        format.html { render :new }
        format.json { render json: @companylicen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companylicens/1
  # PATCH/PUT /companylicens/1.json
  def update
    respond_to do |format|
      if @companylicen.update(companylicen_params)
        format.html { redirect_to @companylicen, notice: 'Companylicen was successfully updated.' }
        format.json { render :show, status: :ok, location: @companylicen }
      else
        format.html { render :edit }
        format.json { render json: @companylicen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companylicens/1
  # DELETE /companylicens/1.json
  def destroy
    @companylicen.destroy
    respond_to do |format|
      format.html { redirect_to companylicens_url, notice: 'Companylicen was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_companylicen
      @companylicen = Companylicen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def companylicen_params
      params.require(:companylicen).permit(:compan_id, :buslicen, :finastate, :qualicert, :orgchart, :safelicen, :forconmanquacert, :statut, :threesyscert, :taxcert, :creditrat, :finastatement, :orgcode, :nolitproof, :nobankcert, :comcontract, :other, :certofaward)
    end
end

app/helpers/companylicens_helper.rb
module CompanylicensHelper
end

app/views/companylicens/_form.html.erb
<script language="JavaScript" type="text/javascript">
    function readURL(input,imgid) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('.'+imgid)
                        .attr('src', e.target.result)
                //.width(300)
                //.height(200);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

<%= form_for(@companylicen) do |f| %>
    <% if @companylicen.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@companylicen.errors.count, "error") %> prohibited this companylicen from being saved:</h2>

          <ul>
            <% @companylicen.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="with-sidebar">
      <div class="container">


        <div class="field">
          <%= f.label :buslicen %><br>
          <%= f.text_area :buslicen, class:"span8"%>
        </div>
        <div class="field">
          <%= f.label :finastate %><br>
          <%= f.text_area :finastate, class:"span8" %>
        </div>
        <div class="field">
          <%= f.label :qualicert %><br>
          <%= f.text_area :qualicert, class:"span8" %>
        </div>
        <div class="field">
          <%= f.label :orgchart %><br>
          <%= f.text_area :orgchart, class:"span8" %>
        </div>


        <div class="span12 field-box">
          <label> <%= f.label :安全许可证 %></label>
          <%= f.file_field :safelicen ,:onchange => "readURL(this,'img1')"%>
          <%if !@companylicen.safelicen%>
              <img style="margin-left: 110px" class="img1" width="200px" height="150px"  src=<%= @companylicen.safelicen.url%> />
          <%else%>
              <img style="margin-left: 110px" class="img1" width="200px" height="150px"  src=<%= image_path('noimage.png')%> />
          <%end%>
        </div>




        <div class="span12 field-box">
          <label> <%= f.label :对外承包经营资格证证 %></label>
          <%= f.file_field :forconmanquacert ,:onchange => "readURL(this,'img2')"%>
          <%if !@companylicen.forconmanquacert%>
              <img style="margin-left: 110px" class="img2" width="200px" height="150px"  src=<%= @companylicen.forconmanquacert.url%> />
          <%else%>
              <img style="margin-left: 110px" class="img2" width="200px" height="150px"  src=<%= image_path('noimage.png')%> />
          <%end%>
        </div>





        <div class="span12 field-box">
          <label> <%= f.label :章程 %></label>
          <%= f.file_field :statut ,:onchange => "readURL(this,'img3')"%>
          <%if !@companylicen.statut%>
              <img style="margin-left: 110px" class="img3" width="200px" height="150px"  src=<%= @companylicen.statut.url%> />
          <%else%>
              <img style="margin-left: 110px" class="img3" width="200px" height="150px"  src=<%= image_path('noimage.png')%> />
          <%end%>
        </div>



        <div class="span12 field-box">
          <label> <%= f.label :三体系证书 %></label>
          <%= f.file_field :threesyscert ,:onchange => "readURL(this,'img4')"%>
          <%if !@companylicen.threesyscert%>
              <img style="margin-left: 110px" class="img4" width="200px" height="150px"  src=<%= @companylicen.threesyscert.url%> />
          <%else%>
              <img style="margin-left: 110px" class="img4" width="200px" height="150px"  src=<%= image_path('noimage.png')%> />
          <%end%>
        </div>





        <div class="span12 field-box">
          <label> <%= f.label :税务证 %></label>
          <%= f.file_field :taxcert ,:onchange => "readURL(this,'img5')"%>
          <%if !@companylicen.taxcert%>
              <img style="margin-left: 110px" class="img5" width="200px" height="150px"  src=<%= @companylicen.taxcert.url%> />
          <%else%>
              <img style="margin-left: 110px" class="img5" width="200px" height="150px"  src=<%= image_path('noimage.png')%> />
          <%end%>
        </div>



        <div class="span12 field-box">
          <label> <%= f.label :信用等级证 %></label>
          <%= f.file_field :creditrat ,:onchange => "readURL(this,'img6')"%>
          <%if !@companylicen.creditrat%>
              <img style="margin-left: 110px" class="img6" width="200px" height="150px"  src=<%= @companylicen.creditrat.url%> />
          <%else%>
              <img style="margin-left: 110px" class="img6" width="200px" height="150px"  src=<%= image_path('noimage.png')%> />
          <%end%>
        </div>




        <div class="span12 field-box">
          <label> <%= f.label :财务报表 %></label>
          <%= f.file_field :finastatement ,:onchange => "readURL(this,'img7')"%>
          <%if !@companylicen.finastatement%>
              <img style="margin-left: 110px" class="img7" width="200px" height="150px"  src=<%= @companylicen.finastatement.url%> />
          <%else%>
              <img style="margin-left: 110px" class="img7" width="200px" height="150px"  src=<%= image_path('noimage.png')%> />
          <%end%>
        </div>



        <div class="span12 field-box">
          <label> <%= f.label :组织机构代码证 %></label>
          <%= f.file_field :orgcode ,:onchange => "readURL(this,'img8')"%>
          <%if !@companylicen.orgcode%>
              <img style="margin-left: 110px" class="img8" width="200px" height="150px"  src=<%= @companylicen.orgcode.url%> />
          <%else%>
              <img style="margin-left: 110px" class="img8" width="200px" height="150px"  src=<%= image_path('noimage.png')%> />
          <%end%>
        </div>



        <div class="span12 field-box">
          <label> <%= f.label :无诉讼证明 %></label>
          <%= f.file_field :nolitproof ,:onchange => "readURL(this,'img9')"%>
          <%if !@companylicen.nolitproof%>
              <img style="margin-left: 110px" class="img9" width="200px" height="150px"  src=<%= @companylicen.nolitproof.url%> />
          <%else%>
              <img style="margin-left: 110px" class="img9" width="200px" height="150px"  src=<%= image_path('noimage.png')%> />
          <%end%>
        </div>



        <div class="span12 field-box">
          <label> <%= f.label :未破产证明 %></label>
          <%= f.file_field :nobankcert ,:onchange => "readURL(this,'img10')"%>
          <%if !@companylicen.nobankcert%>
              <img style="margin-left: 110px" class="img10" width="200px" height="150px"  src=<%= @companylicen.nobankcert.url%> />
          <%else%>
              <img style="margin-left: 110px" class="img10" width="200px" height="150px"  src=<%= image_path('noimage.png')%> />
          <%end%>
        </div>

        <div class="field">
          <%= f.label :公司简介 %><br>
          <%= f.text_area :comcontract, class:"span8" %>
        </div>
        <div class="field">
          <%= f.label :其它 %><br>
          <%= f.text_area :other, class:"span8" %>
        </div>


        <div class="span12 field-box">
          <label> <%= f.label :获奖证书 %></label>
          <%= f.file_field :certofaward ,:onchange => "readURL(this,'img11')"%>
          <%if !@companylicen.certofaward%>
              <img style="margin-left: 110px" class="img11" width="200px" height="150px"  src=<%= @companylicen.certofaward.url%> />
          <%else%>
              <img style="margin-left: 110px" class="img11" width="200px" height="150px"  src=<%= image_path('noimage.png')%> />
          <%end%>
        </div>

        <div class="actions">
          <%= f.submit %>
        </div>

      </div>
    </div>
<% end %>

app/views/companylicens/edit.html.erb
<h1>Editing Companylicen</h1>

<%= render 'form' %>

<%= link_to 'Show', @companylicen %> |
<%= link_to 'Back', companylicens_path %>

app/views/companylicens/index.html.erb
<%= render "head" %>
<%= render "left" %>
<p id="notice"><%= notice %></p>



<div class="content">

  <div class="container-fluid">
    <div id="pad-wrapper">
<div class="table-wrapper products-table">
  <div class="row-fluid head">
    <div class="span12">

<table class="table table-hover">
  <thead>
    <tr>
      <th class="span5">Compan</th>
      <th class="span5">Buslicen</th>
      <th  class="span2">process</th>

    </tr>
  </thead>

  <tbody>
    <% @companylicens.each do |companylicen| %>
      <tr>
        <td><%= companylicen.compan_id %></td>
        <td><%= companylicen.buslicen %></td>

        <td><%= link_to 'Show', companylicen %>
        <%= link_to 'Edit', edit_companylicen_path(companylicen) %>
        <%= link_to 'Destroy', companylicen, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
      <%= link_to 'New Companylicen', new_companylicen_path,class:"pull-right" %>
      </div>
    </div>
  </div>
        </div>
      </div>
    </div>

app/views/companylicens/new.html.erb
<%= render "head" %>
<%= render "left" %>

<%= render 'form' %>



<%= link_to 'Back', companylicens_path %>

app/views/companylicens/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Buslicen:</strong>
  <%= @companylicen.buslicen %>
</p>

<p>
  <strong>Finastate:</strong>
  <%= @companylicen.finastate %>
</p>

<p>
  <strong>Qualicert:</strong>
  <%= @companylicen.qualicert %>
</p>

<p>
  <strong>Orgchart:</strong>
  <%= @companylicen.orgchart %>
</p>

<p>
  <strong>安全许可证:</strong>
  <%= image_tag @companylicen.safelicen.url %>
</p>

<p>
  <strong>对外承包经营资格证证:</strong>

  <%= image_tag @companylicen.forconmanquacert.url %>
</p>

<p>
  <strong>章程:</strong>

  <%= image_tag @companylicen.statut.url %>

</p>

<p>
  <strong>三体系证书:</strong>

  <%= image_tag @companylicen.threesyscert.url %>
</p>

<p>
  <strong>税务证:</strong>

  <%= image_tag @companylicen.taxcert.url %>
</p>

<p>
  <strong>信用等级证:</strong>

  <%= image_tag @companylicen.creditrat.url %>
</p>

<p>
  <strong>财务报表:</strong>

  <%= image_tag @companylicen.finastatement.url %>
</p>

<p>
  <strong>组织机构代码证:</strong>

  <%= image_tag @companylicen.orgcode.url %>
</p>

<p>
  <strong>无诉讼证明:</strong>

  <%= image_tag @companylicen.nolitproof.url %>
</p>

<p>
  <strong>未破产证明:</strong>

  <%= image_tag @companylicen.nobankcert.url %>
</p>

<p>
  <strong>公司简介:</strong>
  <%= @companylicen.comcontract %>
</p>

<p>
  <strong>其它:</strong>
  <%= @companylicen.other %>
</p>

<p>
  <strong>获奖证书:</strong>

  <%= image_tag @companylicen.certofaward.url %>
</p>

<%= link_to 'Edit', edit_companylicen_path(@companylicen) %> |
<%= link_to 'Back', companylicens_path %>