config/routes.rb
Rails.application.routes.draw do

  resources :tests
  get 'homes/index'

  get 'homes/show'
 get 'personnels/index'
  get 'achievements/index'
  resources :admins
  resources :personnels
  resources :companylicens
  resources :achievements
  resources :clas
  resources :homes

  root 'homes#index'

end

app/views/admins/_form.html.erb
<div class="container-fluid">
  <div id="pad-wrapper" class="form-page">
    <div class="row-fluid form-wrapper">
      <!-- left column -->
      <div class="span8 column">
        <%= form_for(@admin) do |f| %>
            <div class="field-box">
              <label>姓名:</label>
              <%= f.text_field :username, class:"span8" %>
            </div>

            <div class="field-box">
              <label>帐号:</label>
              <%= f.text_field :login, class:"span8" %>
            </div>

            <div class="field-box">
              <label>密码:</label>
              <%= f.password_field :password, class:"span8" %>
            </div>

            <div class="field-box">
              <label>确认密码:</label>
              <%= f.password_field :password_confirmation, class:"span8" %>
            </div>


            <label></label>
            <%= f.button :"确定", class:"btn btn-primary" %>
            </div>

        <% end %>
        </div>
  </div>
</div>

app/views/admins/edit.html.erb
<%= render 'head' %>

<%= render 'left' %>

<div class="content">

  <div class="container-fluid">
    <div id="pad-wrapper">
      <div><h2>管理员</h2></div>
      <br/>
      <%= render 'form' %>

    </div>
    <%= link_to '返回', admins_path, class: "btn btn-primary-outline pull-right",'data-no-turbolink'=>true%>
  </div>
</div>
</div>

app/views/admins/index.html.erb
<%= render 'head' %>

<%= render 'left' %>
<div class="container fluid-height clearfix">
  <p id="notice"><%= notice %></p>
  <h2 class="heading">管理员设置</h2>
  <br/>
  <div class="widget-container fluid-height clearfix">
    <table class="table table-hover table-bordered table-striped">
      <thead>
      <tr>
        <th></th>
        <th>用户名</th>
        <th>登录名</th>
        <th>密码</th>
        <th>操作</th>
      </tr>
      </thead>
      <% @admins.each do |admin| %>
          <tr>
            <td width="30px"><i class="icon-user"></i></td>
            <td class="hidden-xs"><%= admin.username %></td>
            <td><%= admin.login %></td>
            <td>******</td>
            <% if admin.login  != 'admin' %>
                <td width="100px" align="center"><%= link_to "", edit_admin_path(admin),  class:"icon-pencil usricons", title: "编辑" %>&nbsp;&nbsp;
                  <%= link_to '', admin, method: :delete, data: { confirm: '确认删除？' },class:"icon-trash usricons", title:"删除" %></td>
            <% else %>
                <td width="100px" align="center"><%= link_to "", edit_admin_path(admin),  class:"icon-pencil usricons", title: "编辑" %></td>
            <% end %>
          </tr>
      <% end %>

    </table>

    <br>



    <%= link_to ' 创建管理员', new_admin_path, class: "icon-plus btn btn-primary-outline pull-right",'data-no-turbolink'=>true%>
  </div>
</div>

app/views/admins/new.html.erb
<%= render 'head' %>

<%= render 'left' %>

<div class="content">

  <div class="container-fluid">
    <div id="pad-wrapper">
      <div><h2>管理员</h2></div>
<%= render 'form' %>

    </div>
    <%= link_to '返回', admins_path, class: "btn btn-primary-outline pull-right",'data-no-turbolink'=>true%>
  </div>
</div>
</div>

app/views/admins/show.html.erb
<h1>Admins#show</h1>
<p>Find me in app/views/admins/show.html.erb</p>