config/routes.rb
Rails.application.routes.draw do

  resources :tests
  get 'homes/index'

  get 'homes/show'
 get 'personnels/index'
  get 'achievements/index'
  resources :admins
  resources :personnels
  resources :companylicens
  resources :achievements
  resources :clas
  resources :homes

  root 'homes#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_head.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">

    <a class="brand" href="index.html"><img src="img/logo.png" /></a>

    <ul class="nav pull-right">


      <li class="dropdown">
        <a href="#">
          Your account
        </a>
      </li>
      <li class="settings hidden-phone">
        <a href="signin.html" role="button">
          <i class="icon-share-alt"></i>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/application/_left.html.erb
<!-- sidebar -->
<div id="sidebar-nav">
  <ul id="dashboard-menu">
    <li>
      <a href="/homes">
        <i class="icon-home"></i>
        <span>首页</span>
      </a>
    </li>
    <li>
      <a class="dropdown-toggle" href="#">
        <%if params[:left]=='adm'%>
        <div class="pointer">
          <div class="arrow"></div>
          <div class="arrow_border"></div>
        </div>
            <%else%>

            <%end%>
        <i class="icon-edit"></i>
        <span>管理员</span>
        <i class="icon-chevron-down"></i>
      </a>
      <ul class="submenu">
        <li><a href="/admins" data-no-turbolink="true">管理员列表</a></li>
        <li><%= link_to '新建管理员',new_admin_path,'data-no-turbolink'=>true%></li>
      </ul>
    </li>
    <li>
      <a class="dropdown-toggle" href="#">
        <%if params[:left]=='per'%>
        <div class="pointer">
          <div class="arrow"></div>
          <div class="arrow_border"></div>
        </div>
        <%else%>

        <%end%>
        <i class="icon-group"></i>
        <span>人员</span>
        <i class="icon-chevron-down"></i>
      </a>
      <ul class="submenu">
        <li><a href="/personnels">人员列表</a></li>
        <li><%= link_to ' 人员录入', new_personnel_path,'data-no-turbolink'=>true%></li>
      </ul>
    </li>
    <li>
      <a class="dropdown-toggle" href="#">
        <%if params[:left]=='com'%>
        <div class="pointer">
          <div class="arrow"></div>
          <div class="arrow_border"></div>
        </div>
        <%else%>

        <%end%>
        <i class="icon-table"></i>
        <span>公司证照</span>
        <i class="icon-chevron-down"></i>
      </a>
      <ul class="submenu">
        <li><a href="/companylicens">公司证照列表</a></li>
        <li><%= link_to '证照录入',new_companylicen_path,'data-no-turbolink'=>true%></li>
      </ul>
    </li>
    <li>
      <a class="dropdown-toggle" href="#">
        <%if params[:left]=='cla'%>
        <div class="pointer">
          <div class="arrow"></div>
          <div class="arrow_border"></div>
        </div>
        <%else%>

        <%end%>
        <i class="icon-random"></i>
        <span>项目类型</span>
        <i class="icon-chevron-down"></i>
      </a>
      <ul class="submenu">
        <li><a href="/clas">项目类型列表</a></li>
        <li><%= link_to '项目类型设置', new_cla_path,'data-no-turbolink'=>true%></li>
      </ul>
    </li>
    <li>
      <a class="dropdown-toggle" href="#">
        <%if params[:left]=='cla'%>
        <div class="pointer">
          <div class="arrow"></div>
          <div class="arrow_border"></div>
        </div>
        <%else%>

        <%end%>
        <i class="icon-code-fork"></i>
        <span>业绩表</span>
        <i class="icon-chevron-down"></i>
      </a>
      <ul class="submenu">
        <li><a href="/achievements">业绩列表</a></li>
        <li><%= link_to '业绩录入', new_achievement_path,'data-no-turbolink'=>true%></li>
      </ul>
    </li>
    <li>
      <a class="dropdown-toggle" href="#">
        <i class="icon-share-alt"></i>
        <span>Extras</span>
        <i class="icon-chevron-down"></i>
      </a>
      <ul class="submenu">
        <li><a href="signup.html">Sign up</a></li>
      </ul>
    </li>
  </ul>
</div>
<!-- end sidebar -->